export * from "./types/index.test.js";

import { Alocer } from "@hazae41/alocer";
import { Base16 } from "@hazae41/base16";
import { Readable } from "@hazae41/binary";
import { Keccak256 } from "@hazae41/keccak256";
import { Morax } from "@hazae41/morax";
import { test } from "@hazae41/phobos";
import { Cubane } from "index.js";
import { tryDecode, tryEncode, tryReadFromBytes } from "./index.js";
import { FunctionSignature } from "./signature/signature.js";
import { StaticAddress } from "./types/address/address.js";
import { createDynamicArray } from "./types/array/array.js";
import { createDynamicTuple } from "./types/tuple/tuple.js";
import { createDynamicVector } from "./types/vector/vector.js";

await Alocer.initBundledOnce()
Base16.set(Base16.fromAlocer(Alocer))

await Morax.initBundledOnce()
Keccak256.set(Keccak256.fromMorax(Morax))

test("test", async () => {
  const abi = "f71870b100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000007b000000000000000000000000000000000000000000000000000000000000000568656c6c6f000000000000000000000000000000000000000000000000000000"
  const signature = FunctionSignature.tryParse("test(bool,string,uint256)").unwrap()
  const bytes = Base16.get().tryPadStartAndDecode(abi).unwrap().copyAndDispose()
  const decoded = tryReadFromBytes(signature, bytes).unwrap()
  console.log(decoded)
})

test("test", async () => {
  const abi = "000000000000000000000000d8da6bf26964af9d7eed9e03e53415d37aa9604500000000000000000000000076a65814b6e0fa5a3598ef6503fa1d990ec0e61a000000000000000000000000d66832ff9d808b32adfe0136a0381054f3600185"
  const bytes = Base16.get().tryPadStartAndDecode(abi).unwrap().copyAndDispose()
  const decoded = Readable.tryReadFromBytes(createDynamicArray(StaticAddress, 3), bytes).unwrap()
  console.log(decoded)
})

test("test", async () => {
  const abi = "00000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000003000000000000000000000000d8da6bf26964af9d7eed9e03e53415d37aa9604500000000000000000000000076a65814b6e0fa5a3598ef6503fa1d990ec0e61a000000000000000000000000d66832ff9d808b32adfe0136a0381054f3600185"
  const bytes = Base16.get().tryPadStartAndDecode(abi).unwrap().copyAndDispose()
  const decoded = Readable.tryReadFromBytes(createDynamicTuple(createDynamicVector(StaticAddress)), bytes).unwrap()
  console.log(decoded.inner)
})

test("runtime encode then decode", async () => {
  const signature = FunctionSignature.tryParse("f(bool,uint256,(string,address[3])[],bytes)").unwrap()

  const hex = tryEncode(signature,
    true,
    123456789n,
    [
      [
        "hello world",
        [
          "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
          "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045",
          "0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"
        ]
      ],
    ],
    new Uint8Array([1, 2, 3])
  ).unwrap()

  const funcAndArgs = tryDecode(signature, hex).unwrap()

  console.log(funcAndArgs.args.inner[2])
})

console.log(FunctionSignature.tryParse("f(bool,uint256,string)").unwrap().codegen())

/**
 * This code was autogenerated
 */
export const f = Cubane.Abi.FunctionSignature.new("f", "f(bool,uint256,string)", Cubane.Abi.createFunctionSelectorAndArguments(Cubane.Abi.FunctionSelector.from([196, 183, 30, 19]), Cubane.Abi.createDynamicTuple(Cubane.Abi.StaticBool, Cubane.Abi.createStaticBigUint(32), Cubane.Abi.DynamicString)))

const hex = tryEncode(f, true, 123456789n, "hello world").unwrap()

console.log(hex)